services:
  web:
    build: .
    command: bash -c "python backend/manage.py migrate && gunicorn --bind 0.0.0.0:8000 backend.core.wsgi:application"
    volumes:
      - ./backend:/app/backend
      - static_volume:/app/backend/static
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    environment:
      - PYTHONPATH=/app/backend
    depends_on:
      - db
      - redis
    restart: always

  db:
    image: postgres:13
    env_file:
      - backend/.env
    environment:
      POSTGRES_DB: book_sphere
      POSTGRES_USER: mirbekov
      POSTGRES_PASSWORD: 1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5431:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: celery -A backend.core worker --loglevel=info
    volumes:
      - ./backend:/app/backend
    env_file:
      - backend/.env
    environment:
      - PYTHONPATH=/app/backend
    depends_on:
      - db
      - redis

  celery_beat:
    build: .
    command: celery -A backend.core beat --loglevel=info
    volumes:
      - ./backend:/app/backend
    env_file:
      - backend/.env
    environment:
      - PYTHONPATH=/app/backend
    depends_on:
      - db
      - redis

volumes:
  static_volume:
  postgres_data:
